import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Stack } from "@mui/material";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [time, setTime] = useState(0);
  const [running, setRunning] = useState(false);
  let intervalId;

  const timer = () => {
    setTime(time + 1);
  };

  if (running) {
    // 1. setInterval() method calls a function or evaluates an expression at specified time intervals
    // 2. The setInterval() method will continue calling the function until we use another method called clearInterval()
    //    or until the window is closed
    // 3. The id value returned from setInterval() is the same id we pass into clearInterval() to stop the interval from
    //    running

    intervalId = setInterval(timer, 1000);
  }
  const stopTimer = () => {
    clearInterval(intervalId);
    setRunning(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Stop Watch</title>
        <meta name="description" content="Generated by create next app" />
        {/* ToDo: fix/1: icon not displaying  */}
        <link rel="icon" href="/stopwatch" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Stop Watch</h1>
        <h1>{time}</h1>
        <Stack spacing={2} direction="row">
          <Button variant="contained" onClick={() => setRunning(true)}>
            Start
          </Button>
          <Button variant="contained" onClick={stopTimer}>
            Stop
          </Button>
          <Button
            variant="contained"
            onClick={() => {
              setTime(0);
              setRunning(false);
            }}
          >
            Reset
          </Button>
        </Stack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
